/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.CarDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Prathamesh
 */
public class UserOptionJPanel extends javax.swing.JPanel {

    private JPanel startCardLayout;
    private CarDirectory carDirectory;
    /**
     * Creates new form UserOptionJPanel
     */

    UserOptionJPanel(JPanel startCardLayout, CarDirectory carDirectory) {
        initComponents();
        this.startCardLayout = startCardLayout;
        this.carDirectory = carDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateDetails = new javax.swing.JButton();
        btnManageDetails = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 0, 0));

        btnCreateDetails.setBackground(new java.awt.Color(0, 0, 0));
        btnCreateDetails.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCreateDetails.setForeground(new java.awt.Color(0, 255, 255));
        btnCreateDetails.setText("Enter Car Details");
        btnCreateDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDetailsActionPerformed(evt);
            }
        });

        btnManageDetails.setBackground(new java.awt.Color(0, 0, 0));
        btnManageDetails.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnManageDetails.setForeground(new java.awt.Color(0, 255, 255));
        btnManageDetails.setText("Manage Car Details");
        btnManageDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btnCreateDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnManageDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDetailsActionPerformed
        // TODO add your handling code here:
        CreateJPanel panel = new CreateJPanel(startCardLayout, carDirectory);
        startCardLayout.add("CreateJPanel",panel);
        CardLayout layout = (CardLayout) startCardLayout.getLayout();
        layout.next(startCardLayout);
    }//GEN-LAST:event_btnCreateDetailsActionPerformed

    private void btnManageDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDetailsActionPerformed
        // TODO add your handling code here:
        ManageJPanel panel = new ManageJPanel(startCardLayout, carDirectory);
        startCardLayout.add("ManageJPanel", panel);
        CardLayout layout = (CardLayout) startCardLayout.getLayout();
        layout.next(startCardLayout);
    }//GEN-LAST:event_btnManageDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateDetails;
    private javax.swing.JButton btnManageDetails;
    // End of variables declaration//GEN-END:variables
}
