/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Abstract.User;
import Business.Users.Customer;
import Business.Users.Supplier;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AEDSpring2019
 */
public class LoginScreen extends javax.swing.JPanel {

    /**
     * Creates new form LoginScreen
     */
    List<User> list;
    JPanel panelRight;
    String role;
    public LoginScreen(String role, JPanel panelRight, List<User> list) {
        initComponents();
        this.list = list;
        this.panelRight = panelRight;
        this.role = role;
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPword = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        comboUser = new javax.swing.JComboBox<Object>();
        txtTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));

        btnSubmit.setText("Login");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        comboUser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtTitle.setText("Supplier Login Screen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSubmit)
                    .addComponent(txtTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPword)
                    .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(722, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitle)
                .addGap(92, 92, 92)
                .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(txtPword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnSubmit)
                .addContainerGap(602, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        if(role.equalsIgnoreCase("Supplier"))
        {
            User u = (User)comboUser.getSelectedItem();
            if(u!=null)
            {
               Supplier s = (Supplier)u;
                 if(s.verify(txtPword.getText()))
                {
                    grantAccessTo(u);

                }

            }
               else
                     JOptionPane.showMessageDialog(null,"Please enter a valid password"+"\nEnsure you have selected correct login id");            
        }
        
        else{
            
            User u = (User)comboUser.getSelectedItem();
            if(u!=null)
            {
                Customer s = (Customer)u;  
                 
                if(s.verify(txtPword.getText()))
                {
                    grantAccessTo(u);

                }
                else
                     JOptionPane.showMessageDialog(null,"Please enter a valid password"+"\nEnsure you have selected correct login id");            
 
            }
            
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    
    private void initialize(){
        //text should either be "Supplier Login Screen" OR "Customer Login Screen"
        //Based on the selection
        txtTitle.setText("****** Login Screen");
        comboUser.removeAllItems();
        if(role.equalsIgnoreCase("Supplier") || role.equalsIgnoreCase("Customer"))
        {
            if(role.equalsIgnoreCase("Supplier"))
                txtTitle.setText("Supplier Login Screen");
            else
               txtTitle.setText("Customer Login Screen"); 
        }
        comboUser.removeAllItems();
        for (User u: list)
        {
            comboUser.addItem(u);
        }
        /*if(role.equalsIgnoreCase("Supplier")){
            txtTitle.setText("Supplier login screen");
        }
        comboUser.removeAllItems();
        for(User u: list){
            comboUser.addItem(u);
        }
        //only customer or suppliers should be listed based on the selection*/
    }
    
    private void grantAccessTo(User u) {
        
        SuccessScreen ss = new SuccessScreen(u);
        CardLayout layout = (CardLayout)panelRight.getLayout();
        panelRight.add(ss);
        layout.next(panelRight);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<Object> comboUser;
    private javax.swing.JTextField txtPword;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables

    
}
